CHECKOUT_STATUS = (
    "CANCELLED",
    "IN_PROGRESS",
    "OK",
    "PENDING",
    "REJECTED",
    "TIMEOUT",
)

PAYMENT_STATUS = (
    "AUTHORIZED",
    "PAID",
    "PARTIALLY_PAID",
    "PARTIALLY_REFUNDED",
    "PENDING",
    "REFUNDED",
    "VOIDED",
)

SHIPMENT_STATUS = (
    "FULFILLED",
    "IN_PROGRESS",
    "ON_HOLD",
    "PARTIALLY_FULFILLED",
    "PENDING",
    "SCHEDULED",
)
